from typing import Any, Dict, List, Optional

__version__: str

DiceResult = Dict[str, Any]
ProgramResult = Dict[str, Any]
RollHistory = List[DiceResult]
ModifierList = List[str]

class ResourcePolicy:
    def __init__(self) -> None: ...
    def with_limit(self, name: str, limit: int) -> ResourcePolicy: ...
    def limits(self) -> Dict[str, int]: ...
    def hard_limits(self) -> Dict[str, int]: ...

class OneRoll:
    def __init__(self, policy: Optional[ResourcePolicy] = ...) -> None: ...
    def roll(self, expression: str) -> DiceResult: ...
    def run(self, program: str) -> ProgramResult: ...
    def roll_multiple(self, expression: str, times: int) -> RollHistory: ...
    def roll_simple(self, dice_count: int, dice_sides: int) -> int: ...
    def roll_with_modifiers(
        self, dice_count: int, dice_sides: int, modifiers: ModifierList
    ) -> DiceResult: ...

def roll_dice(expression: str) -> DiceResult: ...
def run_program(program: str) -> ProgramResult: ...
def roll_simple(dice_count: int, dice_sides: int) -> int: ...
