from typing import Dict, Literal, Mapping, Optional, Sequence, Tuple, Union

CompatibilityMode = Literal["strict_v2", "v1"]
Seed = Union[int, str]
VariableKey = Union[int, str]
HostValue = Union[int, str, bool, Sequence["HostValue"]]
Variables = Mapping[VariableKey, HostValue]
JsonScalar = Union[None, bool, int, str]
JsonValue = Union[JsonScalar, Sequence["JsonValue"], Mapping[str, "JsonValue"]]
JsonObject = Dict[str, JsonValue]

__version__: str

class Span:
    @property
    def start_byte(self) -> int: ...
    @property
    def end_byte(self) -> int: ...
    def to_dict(self) -> JsonObject: ...

class RandomDescriptor:
    @property
    def algorithm(self) -> Literal["oneroll-chacha12-v1"]: ...
    @property
    def seed(self) -> str: ...
    @property
    def rng_words(self) -> int: ...
    def to_dict(self) -> JsonObject: ...

class BatchRandomDescriptor:
    @property
    def algorithm(self) -> Literal["oneroll-sha256-batch-v1"]: ...
    @property
    def seed(self) -> str: ...
    @property
    def samples(self) -> int: ...
    def to_dict(self) -> JsonObject: ...

class BatchFailureDescriptor:
    @property
    def algorithm(self) -> Literal["oneroll-sha256-batch-v1"]: ...
    @property
    def seed(self) -> str: ...
    @property
    def samples(self) -> int: ...
    @property
    def sample_index(self) -> Optional[int]: ...
    def to_dict(self) -> JsonObject: ...

class Diagnostic:
    @property
    def phase(self) -> Literal["parse", "validate", "evaluate", "cancel"]: ...
    @property
    def code(self) -> str: ...
    @property
    def message(self) -> str: ...
    @property
    def span(self) -> Optional[Span]: ...
    @property
    def replacement(self) -> Optional[str]: ...
    def to_dict(self) -> JsonObject: ...

class ScalarValue:
    @property
    def kind(self) -> Literal["scalar"]: ...
    @property
    def value(self) -> int: ...
    def to_dict(self) -> JsonObject: ...

class TextValue:
    @property
    def kind(self) -> Literal["text"]: ...
    @property
    def value(self) -> str: ...
    def to_dict(self) -> JsonObject: ...

class BooleanValue:
    @property
    def kind(self) -> Literal["boolean"]: ...
    @property
    def value(self) -> bool: ...
    def to_dict(self) -> JsonObject: ...

class ValuesValue:
    @property
    def kind(self) -> Literal["values"]: ...
    @property
    def items(self) -> Tuple[Value, ...]: ...
    def to_dict(self) -> JsonObject: ...

class RollReference:
    @property
    def node_id(self) -> str: ...
    @property
    def annotations(self) -> Mapping[str, str]: ...
    def to_dict(self) -> JsonObject: ...

class RollSetValue:
    @property
    def kind(self) -> Literal["roll_set"]: ...
    @property
    def item_kind(self) -> Literal["scalar", "text"]: ...
    @property
    def items(self) -> Tuple[RollReference, ...]: ...
    def to_dict(self) -> JsonObject: ...

Value = Union[ScalarValue, TextValue, BooleanValue, ValuesValue, RollSetValue]

class NestedExecution:
    @property
    def kind(self) -> Literal["repeat_iteration", "branch", "function_call"]: ...
    @property
    def index(self) -> int: ...
    @property
    def label(self) -> Optional[str]: ...
    @property
    def instructions(self) -> Tuple[InstructionResult, ...]: ...
    def to_dict(self) -> JsonObject: ...

class InstructionResult:
    @property
    def id(self) -> str: ...
    @property
    def index(self) -> int: ...
    @property
    def span(self) -> Span: ...
    @property
    def canonical(self) -> str: ...
    @property
    def value(self) -> Value: ...
    @property
    def scalar(self) -> Optional[int]: ...
    @property
    def trace_root(self) -> str: ...
    @property
    def executions(self) -> Tuple[NestedExecution, ...]: ...
    def to_dict(self) -> JsonObject: ...

class RollSource:
    @property
    def kind(self) -> Literal["numeric_die", "range_die", "list_die"]: ...
    @property
    def instruction_id(self) -> str: ...
    @property
    def source_index(self) -> int: ...
    @property
    def draw_index(self) -> int: ...
    @property
    def generation(self) -> int: ...
    @property
    def span(self) -> Span: ...
    def to_dict(self) -> JsonObject: ...

class RollNode:
    @property
    def id(self) -> str: ...
    @property
    def value(self) -> Union[ScalarValue, TextValue]: ...
    @property
    def source(self) -> RollSource: ...
    @property
    def parent_node_id(self) -> Optional[str]: ...
    @property
    def cause_trace_id(self) -> str: ...
    def to_dict(self) -> JsonObject: ...

class TraceAnnotation:
    @property
    def node_id(self) -> str: ...
    @property
    def key(self) -> Literal["color"]: ...
    @property
    def value(self) -> str: ...
    def to_dict(self) -> JsonObject: ...

class TraceData:
    @property
    def operation(self) -> Optional[str]: ...
    @property
    def predicate(self) -> Optional[str]: ...
    @property
    def selected_roll_ids(self) -> Tuple[str, ...]: ...
    @property
    def discarded_roll_ids(self) -> Tuple[str, ...]: ...
    @property
    def generated_roll_ids(self) -> Tuple[str, ...]: ...
    @property
    def source_instruction_ids(self) -> Tuple[str, ...]: ...
    @property
    def branch(self) -> Optional[Literal["true", "false"]]: ...
    @property
    def iteration(self) -> Optional[int]: ...
    @property
    def annotations(self) -> Tuple[TraceAnnotation, ...]: ...
    def to_dict(self) -> JsonObject: ...

class TraceNode:
    @property
    def id(self) -> str: ...
    @property
    def kind(
        self,
    ) -> Literal[
        "literal",
        "variable",
        "source",
        "arithmetic",
        "select",
        "filter",
        "sort",
        "count",
        "reroll",
        "explode",
        "merge",
        "bind",
        "occurrences",
        "paint",
        "split",
        "group",
        "function",
        "branch",
        "projection",
    ]: ...
    @property
    def span(self) -> Optional[Span]: ...
    @property
    def inputs(self) -> Tuple[str, ...]: ...
    @property
    def value(self) -> Value: ...
    @property
    def related_roll_ids(self) -> Tuple[str, ...]: ...
    @property
    def data(self) -> TraceData: ...
    def to_dict(self) -> JsonObject: ...

class ResultMetadata:
    @property
    def compatibility_mode(self) -> CompatibilityMode: ...
    @property
    def random(self) -> RandomDescriptor: ...
    @property
    def warnings(self) -> Tuple[Diagnostic, ...]: ...
    def to_dict(self) -> JsonObject: ...

class ProgramResult:
    @property
    def schema_version(self) -> Literal["2.0"]: ...
    @property
    def kind(self) -> Literal["program_result"]: ...
    @property
    def source(self) -> str: ...
    @property
    def canonical(self) -> str: ...
    @property
    def comment(self) -> Optional[str]: ...
    @property
    def instructions(self) -> Tuple[InstructionResult, ...]: ...
    @property
    def roll_nodes(self) -> Tuple[RollNode, ...]: ...
    @property
    def trace_nodes(self) -> Tuple[TraceNode, ...]: ...
    @property
    def metadata(self) -> ResultMetadata: ...
    def to_dict(self) -> JsonObject: ...

class BatchResult:
    @property
    def schema_version(self) -> Literal["2.0"]: ...
    @property
    def kind(self) -> Literal["batch_result"]: ...
    @property
    def source(self) -> str: ...
    @property
    def canonical(self) -> str: ...
    @property
    def results(self) -> Tuple[ProgramResult, ...]: ...
    @property
    def random(self) -> BatchRandomDescriptor: ...
    def to_dict(self) -> JsonObject: ...

class ParsedProgram:
    @property
    def source(self) -> str: ...
    @property
    def canonical(self) -> str: ...
    @property
    def instruction_count(self) -> int: ...
    def to_dict(self) -> JsonObject: ...

class ValidatedProgram:
    @property
    def source(self) -> str: ...
    @property
    def canonical(self) -> str: ...
    @property
    def instruction_count(self) -> int: ...
    @property
    def warnings(self) -> Tuple[Diagnostic, ...]: ...
    def to_dict(self) -> JsonObject: ...

class ResourcePolicy:
    def __init__(self) -> None: ...
    def with_limit(self, name: str, limit: int) -> ResourcePolicy: ...
    def limits(self) -> Mapping[str, int]: ...
    def hard_limits(self) -> Mapping[str, int]: ...

class CancellationToken:
    def __init__(self) -> None: ...
    def cancel(self) -> None: ...
    @property
    def cancelled(self) -> bool: ...

class OneRollError(ValueError):
    @property
    def phase(self) -> Literal["parse", "validate", "evaluate", "cancel"]: ...
    @property
    def code(self) -> str: ...
    @property
    def message(self) -> str: ...
    @property
    def span(self) -> Optional[Span]: ...
    @property
    def resource(self) -> Optional[str]: ...
    @property
    def used(self) -> Optional[int]: ...
    @property
    def requested(self) -> Optional[int]: ...
    @property
    def limit(self) -> Optional[int]: ...
    @property
    def random(self) -> Optional[RandomDescriptor]: ...
    @property
    def batch(self) -> Optional[BatchFailureDescriptor]: ...
    @property
    def expected(self) -> Tuple[str, ...]: ...
    @property
    def replacement(self) -> Optional[str]: ...
    def to_dict(self) -> JsonObject: ...

class ParseError(OneRollError): ...
class ValidationError(OneRollError): ...
class EvaluationError(OneRollError): ...
class ResourceLimitError(EvaluationError): ...
class RandomError(EvaluationError): ...
class ArithmeticEvaluationError(EvaluationError): ...
class CancellationError(OneRollError): ...
class DeadlineExceededError(CancellationError): ...

class Engine:
    def __init__(
        self,
        *,
        resource_policy: Optional[ResourcePolicy] = ...,
        compatibility_mode: CompatibilityMode = ...,
    ) -> None: ...
    def parse(self, source: str) -> ParsedProgram: ...
    def validate(
        self, source: str, *, variables: Optional[Variables] = ...
    ) -> ValidatedProgram: ...
    def roll(
        self,
        expression: str,
        *,
        variables: Optional[Variables] = ...,
        seed: Optional[Seed] = ...,
        cancellation: Optional[CancellationToken] = ...,
        timeout: Optional[float] = ...,
    ) -> InstructionResult: ...
    def run(
        self,
        program: str,
        *,
        variables: Optional[Variables] = ...,
        seed: Optional[Seed] = ...,
        cancellation: Optional[CancellationToken] = ...,
        timeout: Optional[float] = ...,
    ) -> ProgramResult: ...
    def run_batch(
        self,
        program: str,
        samples: int,
        *,
        variables: Optional[Variables] = ...,
        seed: Optional[Seed] = ...,
        cancellation: Optional[CancellationToken] = ...,
        timeout: Optional[float] = ...,
    ) -> BatchResult: ...

LegacyDiceResult = Dict[str, object]
LegacyProgramResult = Dict[str, object]
LegacyStatistics = Dict[str, object]

class OneRoll:
    def __init__(self, policy: Optional[ResourcePolicy] = ...) -> None: ...
    def roll(self, expression: str) -> LegacyDiceResult: ...
    def run(self, program: str) -> LegacyProgramResult: ...
    def roll_simple(self, dice_count: int, dice_sides: int) -> int: ...
    def roll_multiple(
        self, expression: str, times: int
    ) -> Sequence[LegacyDiceResult]: ...
    def roll_statistics(self, expression: str, times: int) -> LegacyStatistics: ...
    def roll_with_modifiers(
        self, dice_count: int, dice_sides: int, modifiers: Sequence[str]
    ) -> LegacyDiceResult: ...

class CommonRolls:
    D20: str
    D20_ADVANTAGE: str
    D20_DISADVANTAGE: str
    ATTRIBUTE_ROLL: str
    D6_DAMAGE: str
    D8_DAMAGE: str
    D10_DAMAGE: str
    D12_DAMAGE: str
    HIT_POINTS_D6: str
    HIT_POINTS_D8: str
    HIT_POINTS_D10: str
    HIT_POINTS_D12: str

def roll(expression: str) -> LegacyDiceResult: ...
def run(program: str) -> LegacyProgramResult: ...
def roll_simple(dice_count: int, dice_sides: int) -> int: ...
def roll_multiple(expression: str, times: int) -> Sequence[LegacyDiceResult]: ...
def roll_statistics(expression: str, times: int) -> LegacyStatistics: ...
