name: Build and Deploy Docs

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  quality:
    uses: ./.github/workflows/quality.yml

  build:
    needs: quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          version: "0.11.32"

      - name: Install dependencies
        run: uv sync --all-groups --frozen

      - name: Build documentation
        run: uv run --frozen sphinx-build -W --keep-going -b html docs/source docs/_build/html

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.BOT_TOKEN }}
          publish_dir: ./docs/_build/html
          publish_branch: gh-pages
          user_name: "hydroroll-bot"
          user_email: "bot@hydroroll.team"
